import { useEffect, useRef, useState } from 'react';
import { formatEther, formatUnits } from 'viem';
import { loadConfig, site, type Config } from './config';
import { alarmState, errorMessage, type Snapshot } from './chain';
import { useCanary } from './useCanary';
import { useWallet } from './wallet';
import { AddressValue, Arrow, Copy, Field, Seismograph, amount } from './components';
import { Actions } from './Actions';
import { Verify } from './Verify';
import { Integrate } from './Integrate';

type Route = 'status' | 'verify' | 'integrate';
const routeFromHash = (): Route => location.hash === '#verify' ? 'verify' : location.hash === '#integrate' ? 'integrate' : 'status';
function SignalBanner({ snapshot, stale, error }: { snapshot?: Snapshot; stale: boolean; error: string }) {
  const state = snapshot ? alarmState(snapshot) : '';
  const unavailable = !snapshot || stale || !!error || !snapshot.verified;
  const label = !snapshot ? error ? 'SIGNAL UNAVAILABLE' : 'READING THE SIGNAL' : unavailable ? 'OBSERVATION NOT CURRENT' : state;
  const description = !snapshot ? 'Connecting to Ethereum. No alarm state is assumed until the reads complete.' : snapshot.verificationError || (unavailable ? `Last observed: ${state}. Retry reads to restore a verified live signal.` : state === 'TRIPPED' ? 'The live balance is below threshold after arming. Investigate on chain. Poke to record the first observation.' : state === 'AWAITING POKE' ? 'The bounty has reached the threshold. Call poke() to record the balance and arm the alarm.' : state === 'NOT YET FUNDED' ? 'The observed high-water mark is below threshold. Fund the bounty, then poke to arm the alarm.' : 'The observed high-water mark has reached threshold. The live balance remains at or above it.');
  return <div className={`signal-banner ${unavailable ? 'unknown' : state === 'TRIPPED' ? 'tripped' : state === 'ARMED' ? 'armed' : 'waiting'}`} role="status"><div className="signal-icon" aria-hidden="true">{state === 'TRIPPED' && !unavailable ? '!' : state === 'ARMED' && !unavailable ? '●' : '◌'}</div><div><p className="eyebrow">{unavailable ? 'Observation status' : 'Canary state'}</p><h2>{label}</h2><p>{description}</p></div>{state === 'TRIPPED' && <img className="trip-sticker" src="./art/sticker.png" alt="Quantum Canary alarm sticker" width="128" height="128" />}</div>;
}
export function App() {
  const [config, setConfig] = useState<Config>();
  const [configError, setConfigError] = useState('');
  const [route, setRoute] = useState<Route>(routeFromHash);
  const main = useRef<HTMLElement>(null);
  const wallet = useWallet(config);
  const { snapshot, samples, error, loading, stale, refresh } = useCanary(config, wallet.account && !wallet.wrongChain ? wallet.provider : undefined);
  const init = async () => { setConfigError(''); try { setConfig(await loadConfig()); } catch (e) { setConfigError(errorMessage(e)); } };
  useEffect(() => { void init(); }, []);
  useEffect(() => {
    const change = () => { if (location.hash === '#main') { main.current?.focus(); return; } setRoute(routeFromHash()); if (location.hash === '#fund') requestAnimationFrame(() => document.getElementById('fund')?.scrollIntoView({ behavior: 'instant' })); else { window.scrollTo({ top: 0, behavior: 'instant' }); main.current?.focus({ preventScroll: true }); } };
    window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change);
  }, []);
  useEffect(() => { document.title = `${route[0].toUpperCase() + route.slice(1)} — Quantum Canary`; }, [route]);
  return <>
    <a className="skip-link" href="#main" onClick={event => { event.preventDefault(); main.current?.focus(); main.current?.scrollIntoView(); }}>Skip to content</a>
    <div className="topline"><span>Public cryptographic observatory</span><span>ETHEREUM MAINNET <span className="status-dot" /> CHAIN {config?.manifest.chainId ?? '…'}</span></div>
    <header className="site-header"><a className="brand" href="#status" aria-label="Quantum Canary home"><img src="./art/logo.png" alt="" width="46" height="46" /><span>Quantum<br />Canary<span className="brand-period">_</span></span></a><nav aria-label="Main navigation">{(['status', 'verify', 'integrate'] as const).map((r, i) => <a key={r} href={`#${r}`} aria-current={route === r ? 'page' : undefined}><span className="nav-number">0{i + 1}</span>{r[0].toUpperCase() + r.slice(1)}</a>)}</nav><a className="button header-fund" href="#fund">Fund the bounty <span aria-hidden="true">↗</span></a></header>
    <main id="main" ref={main} tabIndex={-1}>
      {configError && <div className="notice" role="alert"><h1>Deployment could not load.</h1><p>{configError}</p><button className="button" onClick={() => void init()}>Retry configuration</button></div>}
      {(error || stale) && <div className="notice error-notice" role="alert"><strong>{stale ? 'Observation is stale.' : 'Live reads unavailable.'}</strong><p>{error || 'No recent Ethereum observation has arrived. Last-known values are shown; transactions are disabled.'}</p><button className="button small" disabled={loading} onClick={() => void refresh()}>{loading ? 'Retrying reads…' : 'Retry reads'}</button></div>}
      <section hidden={route !== 'status'} aria-label="Status page">
        <div className="hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-cross" aria-hidden="true">✳</span> A canary for the quantum age</p><h1>A small bird.<br />A very big <span>warning.</span></h1><p>A public bounty. An unknown private key.<br />If the funds move, our assumptions break.</p><div className="hero-links"><a className="text-link" href="#verify">Verify the mathematics <span aria-hidden="true">→</span></a><span className="fine">No wallet required.</span></div></div><figure className="hero-art"><img src="./art/hero.png" alt="A yellow canary in a miner’s helmet watches over a luminous cryptographic key." width="1600" height="1600" fetchPriority="high" /><figcaption>SPECIMEN 001 / SECP256K1</figcaption></figure></div>
        <section className="monitor panel" aria-labelledby="monitor-title"><div className="monitor-top"><p className="eyebrow" id="monitor-title"><span className={`status-dot ${snapshot?.verified && !stale && !error ? 'live-dot' : 'pending-dot'}`} /> The listening post</p><div className="monitor-controls"><span className="fine">{snapshot ? `Block ${snapshot.block.toLocaleString('en-US')}` : 'Awaiting block'}</span><button className="text-button" disabled={loading || !config} onClick={() => void refresh()}>{loading ? 'Reading…' : 'Refresh ↻'}</button></div></div>
          <div className="balance-header"><div><span className="eyebrow">Canary ETH balance</span><div className="balance-value">{snapshot ? amount(snapshot.balance, 18, 6) : '—'} <span>ETH</span></div></div><div className="balance-meta"><span>{snapshot?.verified && !stale && !error ? '● LIVE OBSERVATION' : '○ WAITING / UNVERIFIED'}</span><p className="fine">Reads every 12s while visible<br />{snapshot ? new Date(Number(snapshot.blockTime) * 1000).toLocaleString('en-GB', { timeZone: 'UTC' }) + ' UTC' : 'No synthetic readings'}</p></div></div>
          <Seismograph samples={samples} threshold={snapshot?.thresholdWei} unavailable={!snapshot} /><SignalBanner snapshot={snapshot} stale={stale} error={error} />
        </section>
        <dl className="metrics"><Field label="Arming threshold" hint={snapshot ? <>thresholdWei · <span className="break">{String(snapshot.thresholdWei)} wei</span></> : 'thresholdWei()'}>{snapshot ? `${formatEther(snapshot.thresholdWei)} ETH` : '—'}</Field><Field label="Observed high-water mark" hint={snapshot ? <span className="break">{String(snapshot.highWaterMark)} wei</span> : 'highWaterMark()'}>{snapshot ? `${amount(snapshot.highWaterMark)} ETH` : '—'}</Field><Field label="Live alarm / isTripped()" hint="A refill can clear this view.">{snapshot ? String(snapshot.isTripped) : '—'}</Field><Field label="Quantum-locked IMD" hint={snapshot?.imdError || 'Same key. No known way out.'}>{snapshot?.imdBalance !== undefined ? `${amount(snapshot.imdBalance, config?.manifest.network.pairToken.decimals)} IMD` : '—'}</Field></dl>
        <div className="trip-record"><span>trippedAt: <strong>{snapshot ? snapshot.trippedAt === 0n ? '0 · not recorded' : `${snapshot.trippedAt} · ${new Date(Number(snapshot.trippedAt) * 1000).toISOString()}` : '—'}</strong></span><span>trippedBlock: <strong>{snapshot ? snapshot.trippedBlock === 0n ? '0 · not recorded' : String(snapshot.trippedBlock) : '—'}</strong></span></div>
        <div className="observation-note"><p><span className="success-text">↳</span> The high-water mark records balances observed by the constructor or <code>poke()</code>. It is not an automatic history of every block.</p><a href="#fund">Fund &amp; poke →</a></div>
        <details className="chain-details"><summary>Inspect exact values &amp; first recorded trip</summary><div className="detail-grid"><dl><Field label="Exact ETH balance">{snapshot ? `${formatEther(snapshot.balance)} ETH / ${snapshot.balance} wei` : '—'}</Field><Field label="trippedAt()">{snapshot ? `${snapshot.trippedAt} ${snapshot.trippedAt ? '· ' + new Date(Number(snapshot.trippedAt) * 1000).toISOString() : '· No trip recorded'}` : '—'}</Field><Field label="trippedBlock()">{snapshot ? snapshot.trippedBlock ? <a href={`${config?.manifest.network.explorer}/block/${snapshot.trippedBlock}`} target="_blank" rel="noreferrer">{String(snapshot.trippedBlock)} <Arrow /></a> : '0 · No trip recorded' : '—'}</Field><Field label="Exact quantum-locked IMD">{snapshot?.imdBalance !== undefined && config ? `${formatUnits(snapshot.imdBalance, config.manifest.network.pairToken.decimals)} IMD / ${snapshot.imdBalance} base units` : 'Unavailable'}</Field></dl><div><h3>Permanent record, live view</h3><p>The first trip recorded by poke remains here forever. A refill can clear <code>isTripped()</code> without erasing these fields. Zero means no trip was recorded; it does not prove no spending occurred.</p>{config && <><p className="fine">IMD token on Ethereum</p><AddressValue value={config.manifest.network.pairToken.address} config={config} label="Copy IMD address" /><p className="fine">IMD sent to the canary is quantum-locked under the same key assumptions. The alarm watches ETH, not token balance.</p></>}</div></div></details>
        {config && <><div className="wallet-strip"><div><p className="eyebrow">Optional / transaction wallet</p>{wallet.account ? <div className="wallet-account"><span className="break">{wallet.account}</span><Copy value={wallet.account} label="Copy wallet address" /><span className={wallet.wrongChain ? 'warning-text' : 'success-text'}>{wallet.wrongChain ? 'Wrong network' : 'Ethereum connected'}</span></div> : <p>Read and verify without connecting. Use a wallet only to fund or poke.</p>}</div>{wallet.account && <button className="button small" onClick={wallet.disconnect}>Disconnect</button>}</div>{wallet.error && <p className="notice error-text" role="alert">{wallet.error}</p>}<Actions config={config} wallet={wallet} snapshot={snapshot} stale={stale} readError={error} refresh={refresh} /></>}
        <section className="manifesto"><img src="./art/mascot.png" alt="" width="160" height="160" loading="lazy" /><div><p className="eyebrow">An open experiment</p><h2>No custodian.<br />No secret back door.<br /><span>Just a very public canary.</span></h2><a className="text-link" href="#integrate">Build with the signal <span aria-hidden="true">→</span></a></div></section>
      </section>
      <section hidden={route !== 'verify'} aria-label="Verify page"><Verify snapshot={snapshot} stale={stale} readError={error} /></section>
      <section hidden={route !== 'integrate'} aria-label="Integrate page">{config ? <Integrate config={config} /> : <div className="page-intro"><h1>Loading integration details…</h1></div>}</section>
    </main>
    <footer className="site-footer"><div><a href="#status" className="footer-brand">Quantum Canary<span>_</span></a><p className="fine">Listen for the break. Verify for yourself.</p></div><nav aria-label="Project links">{config && <a href={`${config.manifest.network.explorer}/address/${config.contract.address}#code`} target="_blank" rel="noreferrer">Verified contract <Arrow /></a>}<a href={site.source} target="_blank" rel="noreferrer">GitHub source <Arrow /></a><a href={site.launch} target="_blank" rel="noreferrer">IMD launch 1213 <Arrow /></a></nav><div className="footer-bottom"><span>Ownerless by design / public by default</span><span>SECP256K1 · KECCAK-256 · ETHEREUM</span></div></footer>
  </>;
}
