import type { Snapshot } from './chain';
import { PublicKey } from './PublicKey';
import type { Config } from './config';
import { AddressValue, Copy } from './components';

export function Integrate({ config, snapshot, stale, readError }: { config: Config; snapshot?: Snapshot; stale: boolean; readError: string }) {
  const address = config.contract.address.toLowerCase();
  const snippet = `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.26;\n\ninterface IQuantumCanary {\n    function isTripped() external view returns (bool);\n    function trippedBlock() external view returns (uint256);\n}\n\n// Add your own pause policy and recovery process.\nabstract contract CanaryGuard {\n    IQuantumCanary public constant CANARY =\n        IQuantumCanary(\n            address(bytes20(hex"${address.slice(2)}"))\n        );\n\n    bool public quantumAlarm;\n    error QuantumAlarm();\n\n    // Anyone can persist the first true reading.\n    // Call this in a successful, separate transaction.\n    function observeCanary() public {\n        if (CANARY.isTripped() || CANARY.trippedBlock() != 0) {\n            quantumAlarm = true;\n        }\n    }\n\n    modifier whenCanaryQuiet() {\n        if (quantumAlarm || CANARY.isTripped()\n            || CANARY.trippedBlock() != 0) {\n            revert QuantumAlarm();\n        }\n        _;\n    }\n\n    // Apply whenCanaryQuiet to sensitive operations.\n}\n`;
  return <>
    <div className="page-intro"><h1>Wire the alarm<br />into your code.</h1><p className="reading">One public view. Your contract decides what happens next. A vault can stop withdrawals. A guard can block signatures. A keeper can record a trip. Nothing responds automatically until you write that response.</p></div>
    <section className="numbered-section" aria-labelledby="observer-title"><h2 id="observer-title"><span>01</span> Read the observer.</h2><p>Ethereum mainnet / chain {config.manifest.chainId} / immutable / ownerless</p><AddressValue value={config.contract.address} config={config} label="Copy observer address" /><PublicKey snapshot={snapshot} stale={stale} readError={readError} compact /><p className="reading">Use this contract for reads and <code>poke()</code>. Send bounty ETH to <code>canaryAddress()</code>, shown on Status. The observer cannot accept donations.</p><div className="abi-download"><a className="button" href={`./${config.contract.abiPath}`} download="QuantumCanary.json">Download full ABI ↓</a><div><span>Canonical ABI Keccak-256</span><code className="break">0x{config.contract.abiHash}</code></div></div></section>
    <section className="numbered-section" aria-labelledby="latch-title"><h2 id="latch-title"><span>02</span> A live check is not a latch.</h2><div className="caveat"><strong>isTripped() can become false again.</strong><p>It checks <code>balance &lt; thresholdWei &amp;&amp; highWaterMark ≥ thresholdWei</code> right now. A third party refilling the canary can clear that live alarm.</p><p>The community hook latches its own retirement after observing a trip. It does not latch a signal for your integration. If you need a permanent signal, <strong>latch the first true reading yourself.</strong></p><p><code>trippedBlock() != 0</code> is permanent evidence only if someone called <code>poke()</code> while the alarm was true. A view call records nothing.</p></div></section>
    <section className="numbered-section" aria-labelledby="snippet-title"><h2 id="snippet-title"><span>03</span> Start with a guard.</h2><div className="code-panel"><div className="code-heading"><span>CanaryGuard.sol</span><Copy value={snippet} label="Copy Solidity" /></div><pre tabIndex={0} aria-label="Solidity integration example"><code>{snippet}</code></pre></div><div className="reading-columns integration-notes"><p><strong>Commit the observation.</strong> Call <code>observeCanary()</code> in a successful transaction to persist the latch. Setting a flag and then reverting in the same transaction rolls the flag back.</p><p><strong>Choose a response.</strong> The guard also checks the live view and the observer’s recorded trip. Add it to the operations you want to stop. Decide how to handle recovery, finality, and keeper failures.</p><p><strong>Fund, then poke.</strong> The observer needs an observed high-water mark at or above its threshold before it can trip. A fall that is never observed cannot be recovered from the getters.</p></div></section>
    <details className="abi-details"><summary>Inspect the full attested ABI</summary><pre tabIndex={0} aria-label="QuantumCanary JSON ABI"><code>{JSON.stringify(config.abi, null, 2)}</code></pre></details>
  </>;
}
