import type { Config } from './config';
import { AddressValue, Copy } from './components';

export function Integrate({ config }: { config: Config }) {
  const address = config.contract.address.toLowerCase();
  const snippet = `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.26;\n\ninterface IQuantumCanary {\n    function isTripped() external view returns (bool);\n    function trippedBlock() external view returns (uint256);\n}\n\n// Example integration: add your own access control,\n// pause policy and recovery process to a real vault.\nabstract contract CanaryGuard {\n    IQuantumCanary public constant CANARY =\n        IQuantumCanary(\n            address(bytes20(hex"${address.slice(2)}"))\n        );\n\n    error QuantumAlarm();\n\n    modifier whenCanaryQuiet() {\n        // Include the recorded alarm to survive a refill.\n        if (CANARY.isTripped() || CANARY.trippedBlock() != 0) {\n            revert QuantumAlarm();\n        }\n        _;\n    }\n\n    // Apply whenCanaryQuiet to sensitive vault operations.\n}\n`;
  return <>
    <div className="page-intro"><div><p className="eyebrow">03 / a signal anyone can use</p><h1>One boolean.<br /><span className="muted">A reason to act.</span></h1><p>Let a vault, multisig, or DAO read the canary before a sensitive operation. The observer is immutable and ownerless. Reads need no wallet and cost no gas off chain.</p></div><div className="boolean-art" aria-hidden="true"><span>isTripped()</span><strong>bool</strong><span>PUBLIC · VIEW</span></div></div>
    <section className="integration-grid"><div className="panel integration-info"><p className="eyebrow">Ethereum / chain ID {config.manifest.chainId}</p><h2>The observer contract</h2><p className="fine">Use this address for reads and poke(). Send bounty ETH to canaryAddress(), shown on Status.</p><AddressValue value={config.contract.address} config={config} label="Copy observer address" /><dl><div><dt>Interface</dt><dd>QuantumCanary</dd></div><div><dt>Access</dt><dd>Public / permissionless</dd></div><div><dt>Updates</dt><dd>No proxy. No owner.</dd></div></dl><a className="button" href={`./${config.contract.abiPath}`} download="QuantumCanary.json">Download full ABI ↓</a><p className="fine">Canonical ABI Keccak-256</p><code className="break fine">0x{config.contract.abiHash}</code></div>
    <div className="code-panel"><div className="code-heading"><span>CanaryGuard.sol</span><Copy value={snippet} label="Copy Solidity" /></div><pre tabIndex={0} aria-label="Solidity integration example"><code>{snippet}</code></pre></div></section>
    <section className="integration-rules section-grid"><div><p className="eyebrow">Integration notes</p><h2>Read the signal.<br />Own the response.</h2></div><div><h3>Live alarm</h3><p><code>isTripped()</code> returns <code>balance &lt; thresholdWei &amp;&amp; highWaterMark ≥ thresholdWei</code>. Calling it does not record a trip or pause another contract.</p><h3>Permanent evidence</h3><p><code>trippedBlock() != 0</code> means a poke recorded a trip. A later refill can clear <code>isTripped()</code>, but cannot erase that record. The example guards against either condition.</p><h3>Vaults, multisigs and DAOs</h3><p>A vault can apply a guard to sensitive operations. A multisig can inspect the view before executing, or install a purpose-built guard. A DAO can use a keeper to propose a response. Nothing pauses automatically unless your integration implements it.</p><h3>Monitoring and finality</h3><p>Someone must poke after funding to arm the observer. Use a keeper to record a suspected trip, confirm canonical blocks, and plan a human review and recovery process. A threshold alarm is one input to your security policy.</p></div></section>
    <details className="abi-details panel"><summary>Inspect the full attested ABI</summary><pre tabIndex={0} aria-label="QuantumCanary JSON ABI"><code>{JSON.stringify(config.abi, null, 2)}</code></pre></details>
  </>;
}
