import { useState, type CSSProperties } from 'react';
import { derive, EXPONENT, hex32, P, type Derivation } from './derive';
import type { Snapshot } from './chain';
import { Copy } from './components';

function Value({ label, value }: { label: string; value: string }) { return <div className="proof-value"><span>{label}</span><code>{value}</code></div>; }
function Compare({ label, computed, onchain }: { label: string; computed: string; onchain: string }) {
  const match = computed.toLowerCase() === onchain.toLowerCase();
  return <div className={`comparison ${match ? 'match' : 'mismatch'}`}><div><strong>{match ? '✓ MATCH' : '✕ MISMATCH'}</strong><span>{label}</span></div><Value label="Computed in this browser" value={computed} /><Value label="Read from contract" value={onchain} /></div>;
}
export function Verify({ snapshot, stale, readError }: { snapshot?: Snapshot; stale: boolean; readError: string }) {
  const [result, setResult] = useState<Derivation>();
  const [phrase, setPhrase] = useState('');
  const [error, setError] = useState('');
  const [run, setRun] = useState(0);
  const validResult = result && phrase === snapshot?.seedPhrase ? result : undefined;
  const allMatch = validResult && snapshot && validResult.seedHash === snapshot.seedHash && validResult.x === snapshot.pubKeyX && validResult.y === snapshot.pubKeyY && validResult.counter === snapshot.counter && validResult.address.toLowerCase() === snapshot.canaryAddress.toLowerCase();
  return <>
    <div className="page-intro"><div><p className="eyebrow">02 / trust nothing. derive everything.</p><h1>Witness the key.<br /><span className="muted">Keep no secrets.</span></h1><p>A public sentence becomes a point on secp256k1. Follow every byte, from the contract’s seed to the bounty address. The arithmetic runs here, in your browser.</p></div><img className="verify-mascot" src="./art/mascot.png" alt="" width="220" height="220" /></div>
    <section className="seed-panel panel" aria-labelledby="seed-title"><p className="eyebrow">The source / seedPhrase()</p><h2 id="seed-title" className="sr-only">The on-chain seed phrase</h2><blockquote>{snapshot ? `“${snapshot.seedPhrase}”` : 'Reading the exact seed phrase from Ethereum…'}</blockquote><div className="seed-credit"><p>Written by the building agent that implemented QuantumCanary.<br /><span className="muted">Public English sentence. Not a wallet recovery phrase.</span></p>{snapshot && <Copy value={snapshot.seedPhrase} label="Copy seed phrase" />}</div>
      {snapshot && <Value label="Contract seedHash() / Keccak-256 of the UTF-8 phrase" value={snapshot.seedHash} />}
    </section>
    <div className="ritual-control"><div><h2>Re-derive it yourself.</h2><p className="fine">Plain JavaScript BigInt for curve arithmetic. Keccak-256 for hashing. No wallet, private key, or signing request.</p></div><button className="button primary" disabled={!snapshot} onClick={() => { if (!snapshot) return; setError(''); try { setResult(derive(snapshot.seedPhrase)); setPhrase(snapshot.seedPhrase); setRun(v => v + 1); } catch (e) { setError((e as Error).message); } }}>{result ? 'Run verification again' : 'Begin verification'} <span aria-hidden="true">→</span></button></div>
    <div role="status">{error && <p className="notice error-text">{error}</p>}{validResult && <p className={`verification-result ${allMatch ? 'match' : 'mismatch'}`}>{allMatch ? '✓ All 5 on-chain comparisons match.' : '✕ Verification mismatch. Do not fund this address.'} {stale || readError ? 'Compared with the last observation; live reads are stale or unavailable.' : `Compared at Ethereum block ${snapshot?.block}.`}</p>}</div>
    {validResult && snapshot ? <ol className="ritual" key={run}>
      <li style={{ '--step': 0 } as CSSProperties}><div className="step-number">01</div><div className="step-body"><p className="eyebrow">The sentence becomes a fingerprint</p><h2>Hash the public seed.</h2><p>Use Ethereum’s Keccak-256 on the exact UTF-8 bytes. No newline, no extra spaces. This hash is not a private key.</p><Compare label="seedHash()" computed={validResult.seedHash} onchain={snapshot.seedHash} /><Value label="Field prime p" value={hex32(P)} /><Value label="Square-root exponent (p + 1) / 4" value={hex32(EXPONENT)} /></div></li>
      <li style={{ '--step': 1 } as CSSProperties}><div className="step-number">02</div><div className="step-body"><p className="eyebrow">The search / start at zero</p><h2>Find a point on the curve.</h2><p>For each counter i, encode two 32-byte words, hash them, then reduce modulo p. Test whether x³ + 7 has a square root in this field.</p>
        {validResult.attempts.map(a => <div className="attempt" key={String(a.i)}><h3>Attempt i = {String(a.i)} <span className={a.accepted ? 'success-text' : 'warning-text'}>{a.accepted ? '✓ accepted' : '↻ rejected; continue'}</span></h3><Value label="abi.encode(seedHash, i) / 64 bytes, big-endian" value={a.encoded} /><Value label="keccak256(encoded)" value={a.digest} /><Value label="x = uint256(hash) mod p" value={hex32(a.x)} /><Value label="rhs = (x³ + 7) mod p" value={hex32(a.rhs)} /><Value label="candidate y = rhs^((p+1)/4) mod p" value={hex32(a.candidateY)} /><Value label="candidate y² mod p" value={hex32(a.square)} /><p className="fine">{a.accepted ? '✓ y² mod p equals rhs. This is the first accepted point.' : '✕ y² mod p differs from rhs. Increment i and try again.'}</p></div>)}
        <Compare label="counter()" computed={String(validResult.counter)} onchain={String(snapshot.counter)} /><Compare label="pubKeyX()" computed={hex32(validResult.x)} onchain={hex32(snapshot.pubKeyX)} /></div></li>
      <li style={{ '--step': 2 } as CSSProperties}><div className="step-number">03</div><div className="step-body"><p className="eyebrow">One point, one convention</p><h2>Choose the even y.</h2><p>{validResult.attempts.at(-1)!.candidateY % 2n ? 'The candidate is odd, so use p − y.' : 'The candidate is already even, so keep it.'} This removes the choice between the two valid roots.</p><Compare label="pubKeyY()" computed={hex32(validResult.y)} onchain={hex32(snapshot.pubKeyY)} /></div></li>
      <li style={{ '--step': 3 } as CSSProperties}><div className="step-number">04</div><div className="step-body"><p className="eyebrow">The destination</p><h2>Turn the point into an address.</h2><p>Concatenate the two 32-byte coordinates, without a 0x04 public-key prefix. Hash the 64 bytes and take the last 20 bytes.</p><Value label="x || y / 64 bytes" value={validResult.packed} /><Value label="keccak256(x || y)" value={validResult.digest} /><Compare label="canaryAddress()" computed={validResult.address} onchain={snapshot.canaryAddress} /></div></li>
    </ol> : <div className="ritual-wait panel"><span aria-hidden="true">[ sentence → hash → point → address ]</span><p>Begin verification to reveal every intermediate value.</p></div>}
    <section className="explanation section-grid"><div><p className="eyebrow">The point of the experiment</p><h2>A public key.<br />An unknown private key.</h2></div><div><p>A normal wallet starts with a secret number and multiplies the curve’s generator to get a public key. This construction goes directly to the public point. It never chooses or computes that secret number.</p><p>A corresponding private key exists, but finding it requires solving the elliptic-curve discrete logarithm problem. Knowing the seed sentence does not give anyone a shortcut under the standard secp256k1 and Keccak assumptions.</p><p>A sufficiently capable quantum computer could solve that problem and sign a transfer. That is why a falling ETH balance is a public signal worth watching.</p><details><summary>Understand the signal’s limits</summary><p>A balance drop alone cannot identify the hardware used. A classical cryptographic breakthrough, address-preimage attack, or Ethereum rule or consensus failure could also break the assumptions.</p><p>The deployed alarm trips only when the balance falls below its threshold after arming. A smaller drop above the threshold does not trip it. A drain and refill between observations can be missed. The first recorded time is when poke observes the trip, not necessarily when the spend happened.</p><p>A refill clears the live view. The first recorded trip remains. Integrations should consider both and wait for appropriate chain finality.</p></details></div></section>
  </>;
}
